runtime: python27
api_version: 1
threadsafe: true

handlers:
# Route localhost:8080/static/* to static/ folder.
- url: /static
  static_dir: static

# Route localhost:8080* (everything else) to 'app' in main.py.
- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
