application: fortune-teller
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
  # /favicon.ico
- url: /themes
  static_dir: themes

#static directories should go ABOVE the catch all url (.*)
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
